/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.emf.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.incquery.patternlanguage.services.PatternLanguageGrammarAccess;
import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class EMFPatternLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class EMFPatternModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EMFPatternModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPatternModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPackageKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPackageNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPackageNameQualifiedNameParserRuleCall_1_1_0 = (RuleCall)cPackageNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cImportPackagesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cImportPackagesXImportSectionParserRuleCall_2_0 = (RuleCall)cImportPackagesAssignment_2.eContents().get(0);
		private final Assignment cPatternsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPatternsPatternParserRuleCall_3_0 = (RuleCall)cPatternsAssignment_3.eContents().get(0);
		
		//EMFPatternModel returns core::PatternModel:
		//	{PatternModel} ("package" packageName=QualifiedName ";"?)? importPackages=XImportSection patterns+=Pattern*;
		public ParserRule getRule() { return rule; }

		//{PatternModel} ("package" packageName=QualifiedName ";"?)? importPackages=XImportSection patterns+=Pattern*
		public Group getGroup() { return cGroup; }

		//{PatternModel}
		public Action getPatternModelAction_0() { return cPatternModelAction_0; }

		//("package" packageName=QualifiedName ";"?)?
		public Group getGroup_1() { return cGroup_1; }

		//"package"
		public Keyword getPackageKeyword_1_0() { return cPackageKeyword_1_0; }

		//packageName=QualifiedName
		public Assignment getPackageNameAssignment_1_1() { return cPackageNameAssignment_1_1; }

		//QualifiedName
		public RuleCall getPackageNameQualifiedNameParserRuleCall_1_1_0() { return cPackageNameQualifiedNameParserRuleCall_1_1_0; }

		//";"?
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//importPackages=XImportSection
		public Assignment getImportPackagesAssignment_2() { return cImportPackagesAssignment_2; }

		//XImportSection
		public RuleCall getImportPackagesXImportSectionParserRuleCall_2_0() { return cImportPackagesXImportSectionParserRuleCall_2_0; }

		//patterns+=Pattern*
		public Assignment getPatternsAssignment_3() { return cPatternsAssignment_3; }

		//Pattern
		public RuleCall getPatternsPatternParserRuleCall_3_0() { return cPatternsPatternParserRuleCall_3_0; }
	}

	public class XImportSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XImportSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXImportSectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cPackageImportAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPackageImportPackageImportParserRuleCall_1_0 = (RuleCall)cPackageImportAssignment_1.eContents().get(0);
		private final Assignment cImportDeclarationsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cImportDeclarationsXImportDeclarationParserRuleCall_2_0 = (RuleCall)cImportDeclarationsAssignment_2.eContents().get(0);
		
		//XImportSection:
		//	{XImportSection} packageImport+=PackageImport* importDeclarations+=XImportDeclaration*;
		public ParserRule getRule() { return rule; }

		//{XImportSection} packageImport+=PackageImport* importDeclarations+=XImportDeclaration*
		public Group getGroup() { return cGroup; }

		//{XImportSection}
		public Action getXImportSectionAction_0() { return cXImportSectionAction_0; }

		//packageImport+=PackageImport*
		public Assignment getPackageImportAssignment_1() { return cPackageImportAssignment_1; }

		//PackageImport
		public RuleCall getPackageImportPackageImportParserRuleCall_1_0() { return cPackageImportPackageImportParserRuleCall_1_0; }

		//importDeclarations+=XImportDeclaration*
		public Assignment getImportDeclarationsAssignment_2() { return cImportDeclarationsAssignment_2; }

		//XImportDeclaration
		public RuleCall getImportDeclarationsXImportDeclarationParserRuleCall_2_0() { return cImportDeclarationsXImportDeclarationParserRuleCall_2_0; }
	}

	public class PackageImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PackageImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEPackageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEPackageEPackageCrossReference_1_0 = (CrossReference)cEPackageAssignment_1.eContents().get(0);
		private final RuleCall cEPackageEPackageSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cEPackageEPackageCrossReference_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//PackageImport:
		//	"import" ePackage=[ecore::EPackage|STRING] ";"? // ('as' alias=ID)?
		//;
		public ParserRule getRule() { return rule; }

		//"import" ePackage=[ecore::EPackage|STRING] ";"? // ('as' alias=ID)?
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//ePackage=[ecore::EPackage|STRING]
		public Assignment getEPackageAssignment_1() { return cEPackageAssignment_1; }

		//[ecore::EPackage|STRING]
		public CrossReference getEPackageEPackageCrossReference_1_0() { return cEPackageEPackageCrossReference_1_0; }

		//STRING
		public RuleCall getEPackageEPackageSTRINGTerminalRuleCall_1_0_1() { return cEPackageEPackageSTRINGTerminalRuleCall_1_0_1; }

		//";"?
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}

	public class XImportDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XImportDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUsesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Assignment cStaticAssignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final Keyword cStaticStaticKeyword_1_0_0_0 = (Keyword)cStaticAssignment_1_0_0.eContents().get(0);
		private final Assignment cExtensionAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final Keyword cExtensionExtensionKeyword_1_0_1_0 = (Keyword)cExtensionAssignment_1_0_1.eContents().get(0);
		private final Assignment cImportedTypeAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final CrossReference cImportedTypeJvmDeclaredTypeCrossReference_1_0_2_0 = (CrossReference)cImportedTypeAssignment_1_0_2.eContents().get(0);
		private final RuleCall cImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_0_2_0_1 = (RuleCall)cImportedTypeJvmDeclaredTypeCrossReference_1_0_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Keyword cAsteriskKeyword_1_0_4 = (Keyword)cGroup_1_0.eContents().get(4);
		private final Assignment cImportedTypeAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final CrossReference cImportedTypeJvmDeclaredTypeCrossReference_1_1_0 = (CrossReference)cImportedTypeAssignment_1_1.eContents().get(0);
		private final RuleCall cImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_1_0_1 = (RuleCall)cImportedTypeJvmDeclaredTypeCrossReference_1_1_0.eContents().get(1);
		private final Assignment cImportedNamespaceAssignment_1_2 = (Assignment)cAlternatives_1.eContents().get(2);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_2_0 = (RuleCall)cImportedNamespaceAssignment_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//XImportDeclaration returns xtype::XImportDeclaration:
		//	"uses" (static?="static" extension?="extension"? importedType=[types::JvmDeclaredType|QualifiedName] "." "*" |
		//	importedType=[types::JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?;
		public ParserRule getRule() { return rule; }

		//"uses" (static?="static" extension?="extension"? importedType=[types::JvmDeclaredType|QualifiedName] "." "*" |
		//importedType=[types::JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?
		public Group getGroup() { return cGroup; }

		//"uses"
		public Keyword getUsesKeyword_0() { return cUsesKeyword_0; }

		//static?="static" extension?="extension"? importedType=[types::JvmDeclaredType|QualifiedName] "." "*" |
		//importedType=[types::JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//static?="static" extension?="extension"? importedType=[types::JvmDeclaredType|QualifiedName] "." "*"
		public Group getGroup_1_0() { return cGroup_1_0; }

		//static?="static"
		public Assignment getStaticAssignment_1_0_0() { return cStaticAssignment_1_0_0; }

		//"static"
		public Keyword getStaticStaticKeyword_1_0_0_0() { return cStaticStaticKeyword_1_0_0_0; }

		//extension?="extension"?
		public Assignment getExtensionAssignment_1_0_1() { return cExtensionAssignment_1_0_1; }

		//"extension"
		public Keyword getExtensionExtensionKeyword_1_0_1_0() { return cExtensionExtensionKeyword_1_0_1_0; }

		//importedType=[types::JvmDeclaredType|QualifiedName]
		public Assignment getImportedTypeAssignment_1_0_2() { return cImportedTypeAssignment_1_0_2; }

		//[types::JvmDeclaredType|QualifiedName]
		public CrossReference getImportedTypeJvmDeclaredTypeCrossReference_1_0_2_0() { return cImportedTypeJvmDeclaredTypeCrossReference_1_0_2_0; }

		//QualifiedName
		public RuleCall getImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_0_2_0_1() { return cImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_0_2_0_1; }

		//"."
		public Keyword getFullStopKeyword_1_0_3() { return cFullStopKeyword_1_0_3; }

		//"*"
		public Keyword getAsteriskKeyword_1_0_4() { return cAsteriskKeyword_1_0_4; }

		//importedType=[types::JvmDeclaredType|QualifiedName]
		public Assignment getImportedTypeAssignment_1_1() { return cImportedTypeAssignment_1_1; }

		//[types::JvmDeclaredType|QualifiedName]
		public CrossReference getImportedTypeJvmDeclaredTypeCrossReference_1_1_0() { return cImportedTypeJvmDeclaredTypeCrossReference_1_1_0; }

		//QualifiedName
		public RuleCall getImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_1_0_1() { return cImportedTypeJvmDeclaredTypeQualifiedNameParserRuleCall_1_1_0_1; }

		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1_2() { return cImportedNamespaceAssignment_1_2; }

		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_2_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_2_0; }

		//";"?
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCheckConstraintParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompareConstraintParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPatternCompositionConstraintParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cPathExpressionConstraintParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEClassifierConstraintParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Constraint returns core::Constraint:
		//	CheckConstraint | CompareConstraint | PatternCompositionConstraint | // Copied from PatternLanguage
		//	PathExpressionConstraint | // Additions
		//	EClassifierConstraint;
		public ParserRule getRule() { return rule; }

		//CheckConstraint | CompareConstraint | PatternCompositionConstraint | // Copied from PatternLanguage
		//PathExpressionConstraint | // Additions
		//EClassifierConstraint
		public Alternatives getAlternatives() { return cAlternatives; }

		//CheckConstraint
		public RuleCall getCheckConstraintParserRuleCall_0() { return cCheckConstraintParserRuleCall_0; }

		//CompareConstraint
		public RuleCall getCompareConstraintParserRuleCall_1() { return cCompareConstraintParserRuleCall_1; }

		//PatternCompositionConstraint
		public RuleCall getPatternCompositionConstraintParserRuleCall_2() { return cPatternCompositionConstraintParserRuleCall_2; }

		//// Copied from PatternLanguage
		//PathExpressionConstraint
		public RuleCall getPathExpressionConstraintParserRuleCall_3() { return cPathExpressionConstraintParserRuleCall_3; }

		//// Additions
		//EClassifierConstraint
		public RuleCall getEClassifierConstraintParserRuleCall_4() { return cEClassifierConstraintParserRuleCall_4; }
	}

	public class EClassifierConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EClassifierConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarVariableReferenceParserRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EClassifierConstraint:
		//	type=Type "(" var=VariableReference ")";
		public ParserRule getRule() { return rule; }

		//type=Type "(" var=VariableReference ")"
		public Group getGroup() { return cGroup; }

		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=VariableReference
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_2_0() { return cVarVariableReferenceParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cClassnameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cClassnameEClassifierCrossReference_1_0 = (CrossReference)cClassnameAssignment_1.eContents().get(0);
		private final RuleCall cClassnameEClassifierIDTerminalRuleCall_1_0_1 = (RuleCall)cClassnameEClassifierCrossReference_1_0.eContents().get(1);
		
		//Type returns core::EntityType:
		//	{ClassType} classname=[ecore::EClassifier];
		public ParserRule getRule() { return rule; }

		//{ClassType} classname=[ecore::EClassifier]
		public Group getGroup() { return cGroup; }

		//{ClassType}
		public Action getClassTypeAction_0() { return cClassTypeAction_0; }

		//classname=[ecore::EClassifier]
		public Assignment getClassnameAssignment_1() { return cClassnameAssignment_1; }

		//[ecore::EClassifier]
		public CrossReference getClassnameEClassifierCrossReference_1_0() { return cClassnameEClassifierCrossReference_1_0; }

		//ID
		public RuleCall getClassnameEClassifierIDTerminalRuleCall_1_0_1() { return cClassnameEClassifierIDTerminalRuleCall_1_0_1; }
	}

	public class RefTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RefType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReferenceTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cRefnameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRefnameEStructuralFeatureCrossReference_1_0 = (CrossReference)cRefnameAssignment_1.eContents().get(0);
		private final RuleCall cRefnameEStructuralFeatureIDTerminalRuleCall_1_0_1 = (RuleCall)cRefnameEStructuralFeatureCrossReference_1_0.eContents().get(1);
		
		//RefType returns core::RelationType:
		//	{ReferenceType} refname=[ecore::EStructuralFeature];
		public ParserRule getRule() { return rule; }

		//{ReferenceType} refname=[ecore::EStructuralFeature]
		public Group getGroup() { return cGroup; }

		//{ReferenceType}
		public Action getReferenceTypeAction_0() { return cReferenceTypeAction_0; }

		//refname=[ecore::EStructuralFeature]
		public Assignment getRefnameAssignment_1() { return cRefnameAssignment_1; }

		//[ecore::EStructuralFeature]
		public CrossReference getRefnameEStructuralFeatureCrossReference_1_0() { return cRefnameEStructuralFeatureCrossReference_1_0; }

		//ID
		public RuleCall getRefnameEStructuralFeatureIDTerminalRuleCall_1_0_1() { return cRefnameEStructuralFeatureIDTerminalRuleCall_1_0_1; }
	}

	public class LiteralValueReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LiteralValueReference");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDoubleValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBoolValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//LiteralValueReference returns core::ValueReference:
		//	IntValue | StringValue | DoubleValue | //Copied from PatternLanguage 
		//	BoolValue | //Additions
		//	EnumValue;
		public ParserRule getRule() { return rule; }

		//IntValue | StringValue | DoubleValue | //Copied from PatternLanguage 
		//BoolValue | //Additions
		//EnumValue
		public Alternatives getAlternatives() { return cAlternatives; }

		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }

		//StringValue
		public RuleCall getStringValueParserRuleCall_1() { return cStringValueParserRuleCall_1; }

		//DoubleValue
		public RuleCall getDoubleValueParserRuleCall_2() { return cDoubleValueParserRuleCall_2; }

		////Copied from PatternLanguage 
		//BoolValue
		public RuleCall getBoolValueParserRuleCall_3() { return cBoolValueParserRuleCall_3; }

		////Additions
		//EnumValue
		public RuleCall getEnumValueParserRuleCall_4() { return cEnumValueParserRuleCall_4; }
	}

	public class EnumValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EnumValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEnumerationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEnumerationEEnumCrossReference_0_0 = (CrossReference)cEnumerationAssignment_0.eContents().get(0);
		private final RuleCall cEnumerationEEnumIDTerminalRuleCall_0_0_1 = (RuleCall)cEnumerationEEnumCrossReference_0_0.eContents().get(1);
		private final Keyword cColonColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLiteralAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cLiteralEEnumLiteralCrossReference_2_0 = (CrossReference)cLiteralAssignment_2.eContents().get(0);
		private final RuleCall cLiteralEEnumLiteralIDTerminalRuleCall_2_0_1 = (RuleCall)cLiteralEEnumLiteralCrossReference_2_0.eContents().get(1);
		
		//EnumValue:
		//	enumeration=[ecore::EEnum]? "::" literal=[ecore::EEnumLiteral];
		public ParserRule getRule() { return rule; }

		//enumeration=[ecore::EEnum]? "::" literal=[ecore::EEnumLiteral]
		public Group getGroup() { return cGroup; }

		//enumeration=[ecore::EEnum]?
		public Assignment getEnumerationAssignment_0() { return cEnumerationAssignment_0; }

		//[ecore::EEnum]
		public CrossReference getEnumerationEEnumCrossReference_0_0() { return cEnumerationEEnumCrossReference_0_0; }

		//ID
		public RuleCall getEnumerationEEnumIDTerminalRuleCall_0_0_1() { return cEnumerationEEnumIDTerminalRuleCall_0_0_1; }

		//"::"
		public Keyword getColonColonKeyword_1() { return cColonColonKeyword_1; }

		//literal=[ecore::EEnumLiteral]
		public Assignment getLiteralAssignment_2() { return cLiteralAssignment_2; }

		//[ecore::EEnumLiteral]
		public CrossReference getLiteralEEnumLiteralCrossReference_2_0() { return cLiteralEEnumLiteralCrossReference_2_0; }

		//ID
		public RuleCall getLiteralEEnumLiteralIDTerminalRuleCall_2_0_1() { return cLiteralEEnumLiteralIDTerminalRuleCall_2_0_1; }
	}
	
	
	private EMFPatternModelElements pEMFPatternModel;
	private XImportSectionElements pXImportSection;
	private PackageImportElements pPackageImport;
	private XImportDeclarationElements pXImportDeclaration;
	private ConstraintElements pConstraint;
	private EClassifierConstraintElements pEClassifierConstraint;
	private TypeElements pType;
	private RefTypeElements pRefType;
	private LiteralValueReferenceElements pLiteralValueReference;
	private EnumValueElements pEnumValue;
	
	private final Grammar grammar;

	private PatternLanguageGrammarAccess gaPatternLanguage;

	@Inject
	public EMFPatternLanguageGrammarAccess(GrammarProvider grammarProvider,
		PatternLanguageGrammarAccess gaPatternLanguage) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaPatternLanguage = gaPatternLanguage;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.incquery.patternlanguage.emf.EMFPatternLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public PatternLanguageGrammarAccess getPatternLanguageGrammarAccess() {
		return gaPatternLanguage;
	}

	
	//EMFPatternModel returns core::PatternModel:
	//	{PatternModel} ("package" packageName=QualifiedName ";"?)? importPackages=XImportSection patterns+=Pattern*;
	public EMFPatternModelElements getEMFPatternModelAccess() {
		return (pEMFPatternModel != null) ? pEMFPatternModel : (pEMFPatternModel = new EMFPatternModelElements());
	}
	
	public ParserRule getEMFPatternModelRule() {
		return getEMFPatternModelAccess().getRule();
	}

	//XImportSection:
	//	{XImportSection} packageImport+=PackageImport* importDeclarations+=XImportDeclaration*;
	public XImportSectionElements getXImportSectionAccess() {
		return (pXImportSection != null) ? pXImportSection : (pXImportSection = new XImportSectionElements());
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//PackageImport:
	//	"import" ePackage=[ecore::EPackage|STRING] ";"? // ('as' alias=ID)?
	//;
	public PackageImportElements getPackageImportAccess() {
		return (pPackageImport != null) ? pPackageImport : (pPackageImport = new PackageImportElements());
	}
	
	public ParserRule getPackageImportRule() {
		return getPackageImportAccess().getRule();
	}

	//XImportDeclaration returns xtype::XImportDeclaration:
	//	"uses" (static?="static" extension?="extension"? importedType=[types::JvmDeclaredType|QualifiedName] "." "*" |
	//	importedType=[types::JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XImportDeclarationElements getXImportDeclarationAccess() {
		return (pXImportDeclaration != null) ? pXImportDeclaration : (pXImportDeclaration = new XImportDeclarationElements());
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//Constraint returns core::Constraint:
	//	CheckConstraint | CompareConstraint | PatternCompositionConstraint | // Copied from PatternLanguage
	//	PathExpressionConstraint | // Additions
	//	EClassifierConstraint;
	public ConstraintElements getConstraintAccess() {
		return (pConstraint != null) ? pConstraint : (pConstraint = new ConstraintElements());
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//EClassifierConstraint:
	//	type=Type "(" var=VariableReference ")";
	public EClassifierConstraintElements getEClassifierConstraintAccess() {
		return (pEClassifierConstraint != null) ? pEClassifierConstraint : (pEClassifierConstraint = new EClassifierConstraintElements());
	}
	
	public ParserRule getEClassifierConstraintRule() {
		return getEClassifierConstraintAccess().getRule();
	}

	//Type returns core::EntityType:
	//	{ClassType} classname=[ecore::EClassifier];
	public TypeElements getTypeAccess() {
		return (pType != null) ? pType : (pType = new TypeElements());
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//RefType returns core::RelationType:
	//	{ReferenceType} refname=[ecore::EStructuralFeature];
	public RefTypeElements getRefTypeAccess() {
		return (pRefType != null) ? pRefType : (pRefType = new RefTypeElements());
	}
	
	public ParserRule getRefTypeRule() {
		return getRefTypeAccess().getRule();
	}

	//LiteralValueReference returns core::ValueReference:
	//	IntValue | StringValue | DoubleValue | //Copied from PatternLanguage 
	//	BoolValue | //Additions
	//	EnumValue;
	public LiteralValueReferenceElements getLiteralValueReferenceAccess() {
		return (pLiteralValueReference != null) ? pLiteralValueReference : (pLiteralValueReference = new LiteralValueReferenceElements());
	}
	
	public ParserRule getLiteralValueReferenceRule() {
		return getLiteralValueReferenceAccess().getRule();
	}

	//EnumValue:
	//	enumeration=[ecore::EEnum]? "::" literal=[ecore::EEnumLiteral];
	public EnumValueElements getEnumValueAccess() {
		return (pEnumValue != null) ? pEnumValue : (pEnumValue = new EnumValueElements());
	}
	
	public ParserRule getEnumValueRule() {
		return getEnumValueAccess().getRule();
	}

	//PatternModel:
	//	("package" packageName=QualifiedName)? patterns+=Pattern*;
	public PatternLanguageGrammarAccess.PatternModelElements getPatternModelAccess() {
		return gaPatternLanguage.getPatternModelAccess();
	}
	
	public ParserRule getPatternModelRule() {
		return getPatternModelAccess().getRule();
	}

	//Pattern:
	//	annotations+=Annotation* modifiers+=Modifiers* "pattern" name=ID "(" (parameters+=Parameter (","
	//	parameters+=Parameter)*)? ")" "="? bodies+=PatternBody ("or" bodies+=PatternBody)*;
	public PatternLanguageGrammarAccess.PatternElements getPatternAccess() {
		return gaPatternLanguage.getPatternAccess();
	}
	
	public ParserRule getPatternRule() {
		return getPatternAccess().getRule();
	}

	//Annotation:
	//	"@" name=ID ("(" parameters+=AnnotationParameter ("," parameters+=AnnotationParameter)* ")")?;
	public PatternLanguageGrammarAccess.AnnotationElements getAnnotationAccess() {
		return gaPatternLanguage.getAnnotationAccess();
	}
	
	public ParserRule getAnnotationRule() {
		return getAnnotationAccess().getRule();
	}

	//AnnotationParameter:
	//	name=ID "=" value=AnnotationValueReference;
	public PatternLanguageGrammarAccess.AnnotationParameterElements getAnnotationParameterAccess() {
		return gaPatternLanguage.getAnnotationParameterAccess();
	}
	
	public ParserRule getAnnotationParameterRule() {
		return getAnnotationParameterAccess().getRule();
	}

	//Modifiers: //injective?='injective' &
	//	private?="private";
	public PatternLanguageGrammarAccess.ModifiersElements getModifiersAccess() {
		return gaPatternLanguage.getModifiersAccess();
	}
	
	public ParserRule getModifiersRule() {
		return getModifiersAccess().getRule();
	}

	//Variable returns types::JvmIdentifiableElement:
	//	{Variable} name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.VariableElements getVariableAccess() {
		return gaPatternLanguage.getVariableAccess();
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}

	//ParameterRef returns Variable:
	//	{ParameterRef} name=ID referredParam=[Variable] (":" type=Type)?;
	public PatternLanguageGrammarAccess.ParameterRefElements getParameterRefAccess() {
		return gaPatternLanguage.getParameterRefAccess();
	}
	
	public ParserRule getParameterRefRule() {
		return getParameterRefAccess().getRule();
	}

	//Parameter returns Variable:
	//	name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.ParameterElements getParameterAccess() {
		return gaPatternLanguage.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//LocalVariable returns Variable:
	//	{LocalVariable} name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.LocalVariableElements getLocalVariableAccess() {
		return gaPatternLanguage.getLocalVariableAccess();
	}
	
	public ParserRule getLocalVariableRule() {
		return getLocalVariableAccess().getRule();
	}

	//VariableReference:
	//	var=ID;
	public PatternLanguageGrammarAccess.VariableReferenceElements getVariableReferenceAccess() {
		return gaPatternLanguage.getVariableReferenceAccess();
	}
	
	public ParserRule getVariableReferenceRule() {
		return getVariableReferenceAccess().getRule();
	}

	//PatternBody:
	//	{PatternBody} name=ID? "{" (constraints+=Constraint ";")* "}";
	public PatternLanguageGrammarAccess.PatternBodyElements getPatternBodyAccess() {
		return gaPatternLanguage.getPatternBodyAccess();
	}
	
	public ParserRule getPatternBodyRule() {
		return getPatternBodyAccess().getRule();
	}

	//PatternCompositionConstraint returns Constraint:
	//	{PatternCompositionConstraint} negative?="neg"? call=PatternCall;
	public PatternLanguageGrammarAccess.PatternCompositionConstraintElements getPatternCompositionConstraintAccess() {
		return gaPatternLanguage.getPatternCompositionConstraintAccess();
	}
	
	public ParserRule getPatternCompositionConstraintRule() {
		return getPatternCompositionConstraintAccess().getRule();
	}

	////'count' 'find' patternRef=[Pattern] '(' (parameters+=ValueReference (','
	////parameters+=ValueReference)*)? ')';
	//PatternCall:
	//	"find" patternRef=[Pattern|QualifiedName] transitive?="+"? "(" (parameters+=ValueReference (","
	//	parameters+=ValueReference)*)? ")";
	public PatternLanguageGrammarAccess.PatternCallElements getPatternCallAccess() {
		return gaPatternLanguage.getPatternCallAccess();
	}
	
	public ParserRule getPatternCallRule() {
		return getPatternCallAccess().getRule();
	}

	//CompareConstraint returns Constraint:
	//	{CompareConstraint} leftOperand=ValueReference feature=CompareFeature rightOperand=ValueReference;
	public PatternLanguageGrammarAccess.CompareConstraintElements getCompareConstraintAccess() {
		return gaPatternLanguage.getCompareConstraintAccess();
	}
	
	public ParserRule getCompareConstraintRule() {
		return getCompareConstraintAccess().getRule();
	}

	//enum CompareFeature:
	//	equality="==" | inequality="!=";
	public PatternLanguageGrammarAccess.CompareFeatureElements getCompareFeatureAccess() {
		return gaPatternLanguage.getCompareFeatureAccess();
	}
	
	public EnumRule getCompareFeatureRule() {
		return getCompareFeatureAccess().getRule();
	}

	//CheckConstraint returns Constraint:
	//	{CheckConstraint} "check" "(" expression=XExpression ")";
	public PatternLanguageGrammarAccess.CheckConstraintElements getCheckConstraintAccess() {
		return gaPatternLanguage.getCheckConstraintAccess();
	}
	
	public ParserRule getCheckConstraintRule() {
		return getCheckConstraintAccess().getRule();
	}

	//PathExpressionConstraint returns Constraint:
	//	{PathExpressionConstraint} head=PathExpressionHead;
	public PatternLanguageGrammarAccess.PathExpressionConstraintElements getPathExpressionConstraintAccess() {
		return gaPatternLanguage.getPathExpressionConstraintAccess();
	}
	
	public ParserRule getPathExpressionConstraintRule() {
		return getPathExpressionConstraintAccess().getRule();
	}

	//PathExpressionHead returns PathExpressionElement:
	//	{PathExpressionHead} type=Type "." tail=PathExpressionTail "(" src=VariableReference "," dst=ValueReference ")";
	public PatternLanguageGrammarAccess.PathExpressionHeadElements getPathExpressionHeadAccess() {
		return gaPatternLanguage.getPathExpressionHeadAccess();
	}
	
	public ParserRule getPathExpressionHeadRule() {
		return getPathExpressionHeadAccess().getRule();
	}

	//PathExpressionTail returns PathExpressionElement:
	//	{PathExpressionTail} type=RefType ("[" index=INT "]")? closure?="*"? ("." tail=PathExpressionTail)?;
	public PatternLanguageGrammarAccess.PathExpressionTailElements getPathExpressionTailAccess() {
		return gaPatternLanguage.getPathExpressionTailAccess();
	}
	
	public ParserRule getPathExpressionTailRule() {
		return getPathExpressionTailAccess().getRule();
	}

	//ValueReference:
	//	LiteralValueReference | VariableValue | ComputationValue;
	public PatternLanguageGrammarAccess.ValueReferenceElements getValueReferenceAccess() {
		return gaPatternLanguage.getValueReferenceAccess();
	}
	
	public ParserRule getValueReferenceRule() {
		return getValueReferenceAccess().getRule();
	}

	//AnnotationValueReference returns ValueReference:
	//	ValueReference | ListValue;
	public PatternLanguageGrammarAccess.AnnotationValueReferenceElements getAnnotationValueReferenceAccess() {
		return gaPatternLanguage.getAnnotationValueReferenceAccess();
	}
	
	public ParserRule getAnnotationValueReferenceRule() {
		return getAnnotationValueReferenceAccess().getRule();
	}

	//IntValue returns LiteralValueReference:
	//	{IntValue} value=INTNUMBER;
	public PatternLanguageGrammarAccess.IntValueElements getIntValueAccess() {
		return gaPatternLanguage.getIntValueAccess();
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}

	//INTNUMBER returns ecore::EInt:
	//	"-"? INT;
	public PatternLanguageGrammarAccess.INTNUMBERElements getINTNUMBERAccess() {
		return gaPatternLanguage.getINTNUMBERAccess();
	}
	
	public ParserRule getINTNUMBERRule() {
		return getINTNUMBERAccess().getRule();
	}

	//StringValue returns LiteralValueReference:
	//	{StringValue} value=STRING;
	public PatternLanguageGrammarAccess.StringValueElements getStringValueAccess() {
		return gaPatternLanguage.getStringValueAccess();
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}

	//BoolValue returns LiteralValueReference:
	//	{BoolValue} value=BOOLEAN;
	public PatternLanguageGrammarAccess.BoolValueElements getBoolValueAccess() {
		return gaPatternLanguage.getBoolValueAccess();
	}
	
	public ParserRule getBoolValueRule() {
		return getBoolValueAccess().getRule();
	}

	//BOOLEAN returns ecore::EBoolean:
	//	"true" | "false" | "TRUE" | "FALSE";
	public PatternLanguageGrammarAccess.BOOLEANElements getBOOLEANAccess() {
		return gaPatternLanguage.getBOOLEANAccess();
	}
	
	public ParserRule getBOOLEANRule() {
		return getBOOLEANAccess().getRule();
	}

	//DoubleValue returns LiteralValueReference:
	//	{DoubleValue} value=DOUBLE;
	public PatternLanguageGrammarAccess.DoubleValueElements getDoubleValueAccess() {
		return gaPatternLanguage.getDoubleValueAccess();
	}
	
	public ParserRule getDoubleValueRule() {
		return getDoubleValueAccess().getRule();
	}

	//DOUBLE returns ecore::EDouble:
	//	"-"? INT "." INT;
	public PatternLanguageGrammarAccess.DOUBLEElements getDOUBLEAccess() {
		return gaPatternLanguage.getDOUBLEAccess();
	}
	
	public ParserRule getDOUBLERule() {
		return getDOUBLEAccess().getRule();
	}

	//VariableValue returns ValueReference:
	//	{VariableValue} value=VariableReference;
	public PatternLanguageGrammarAccess.VariableValueElements getVariableValueAccess() {
		return gaPatternLanguage.getVariableValueAccess();
	}
	
	public ParserRule getVariableValueRule() {
		return getVariableValueAccess().getRule();
	}

	//ListValue returns LiteralValueReference:
	//	{ListValue} "{" values+=ValueReference ("," values+=ValueReference)* "}";
	public PatternLanguageGrammarAccess.ListValueElements getListValueAccess() {
		return gaPatternLanguage.getListValueAccess();
	}
	
	public ParserRule getListValueRule() {
		return getListValueAccess().getRule();
	}

	//ComputationValue returns ValueReference:
	//	AggregatedValue;
	public PatternLanguageGrammarAccess.ComputationValueElements getComputationValueAccess() {
		return gaPatternLanguage.getComputationValueAccess();
	}
	
	public ParserRule getComputationValueRule() {
		return getComputationValueAccess().getRule();
	}

	//AggregatedValue returns ComputationValue:
	//	{AggregatedValue} / *'aggregate'* / aggregator=AggregatorExpression call=PatternCall;
	public PatternLanguageGrammarAccess.AggregatedValueElements getAggregatedValueAccess() {
		return gaPatternLanguage.getAggregatedValueAccess();
	}
	
	public ParserRule getAggregatedValueRule() {
		return getAggregatedValueAccess().getRule();
	}

	//AggregatorExpression:
	//	{CountAggregator} "count";
	public PatternLanguageGrammarAccess.AggregatorExpressionElements getAggregatorExpressionAccess() {
		return gaPatternLanguage.getAggregatorExpressionAccess();
	}
	
	public ParserRule getAggregatorExpressionRule() {
		return getAggregatorExpressionAccess().getRule();
	}

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaPatternLanguage.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaPatternLanguage.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaPatternLanguage.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaPatternLanguage.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaPatternLanguage.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaPatternLanguage.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaPatternLanguage.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaPatternLanguage.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaPatternLanguage.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaPatternLanguage.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaPatternLanguage.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaPatternLanguage.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaPatternLanguage.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaPatternLanguage.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaPatternLanguage.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaPatternLanguage.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaPatternLanguage.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaPatternLanguage.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaPatternLanguage.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaPatternLanguage.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaPatternLanguage.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] (=> explicitOperationCall?="("
	//	(memberCallArguments+=XShortClosure | memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")?
	//	memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaPatternLanguage.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression | XForLoopExpression
	//	| XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression | XTryCatchFinallyExpression |
	//	XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaPatternLanguage.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaPatternLanguage.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaPatternLanguage.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaPatternLanguage.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaPatternLanguage.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaPatternLanguage.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaPatternLanguage.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaPatternLanguage.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaPatternLanguage.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaPatternLanguage.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaPatternLanguage.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaPatternLanguage.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaPatternLanguage.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaPatternLanguage.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaPatternLanguage.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaPatternLanguage.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaPatternLanguage.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaPatternLanguage.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaPatternLanguage.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaPatternLanguage.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaPatternLanguage.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaPatternLanguage.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaPatternLanguage.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaPatternLanguage.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaPatternLanguage.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaPatternLanguage.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaPatternLanguage.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaPatternLanguage.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaPatternLanguage.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaPatternLanguage.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaPatternLanguage.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaPatternLanguage.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaPatternLanguage.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaPatternLanguage.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaPatternLanguage.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaPatternLanguage.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaPatternLanguage.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaPatternLanguage.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaPatternLanguage.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaPatternLanguage.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaPatternLanguage.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaPatternLanguage.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaPatternLanguage.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaPatternLanguage.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaPatternLanguage.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaPatternLanguage.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaPatternLanguage.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaPatternLanguage.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaPatternLanguage.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaPatternLanguage.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaPatternLanguage.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaPatternLanguage.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaPatternLanguage.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaPatternLanguage.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaPatternLanguage.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaPatternLanguage.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaPatternLanguage.getANY_OTHERRule();
	} 
}
