/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema.impl.std;

import de.uni_koblenz.jgralab.impl.std.ReversedEdgeImpl;
import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.Graph;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.exception.GraphIOException;

import de.uni_koblenz.jgralab.demo.schema.Node;

import java.io.IOException;

public class ReversedInheritanceImpl extends ReversedEdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.jgralab.demo.schema.Inheritance {

	ReversedInheritanceImpl(EdgeImpl e, Graph g) {
		super(e, g);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.EdgeClass getAttributedElementClass() {
		return getNormalEdge().getAttributedElementClass();
	}

	public java.lang.String get_child() {
		return ((de.uni_koblenz.jgralab.demo.schema.Inheritance)normalEdge).get_child();
	}

	public void set_child(java.lang.String _child) {
		((de.uni_koblenz.jgralab.demo.schema.Inheritance)normalEdge).set_child(_child);
	}

	public java.lang.String get_parent() {
		return ((de.uni_koblenz.jgralab.demo.schema.Inheritance)normalEdge).get_parent();
	}

	public void set_parent(java.lang.String _parent) {
		((de.uni_koblenz.jgralab.demo.schema.Inheritance)normalEdge).set_parent(_parent);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValues for reversed Edges.");
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		throw new GraphIOException("Can not call readAttributeValuesFromString for reversed Edges.");
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		throw new GraphIOException("Can not call writeAttributeValues for reversed Edges.");
	}

	public String writeAttributeValueToString(String _attributeName) throws IOException, GraphIOException {
		throw new GraphIOException("Can not call writeAttributeValueToString for reversed Edges.");
	}

	public de.uni_koblenz.jgralab.demo.schema.Inheritance getNextInheritanceInGraph() {
		return ((de.uni_koblenz.jgralab.demo.schema.Inheritance)normalEdge).getNextInheritanceInGraph();
	}

	public de.uni_koblenz.jgralab.demo.schema.Inheritance getNextInheritanceIncidence() {
		return (de.uni_koblenz.jgralab.demo.schema.Inheritance)getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Inheritance.EC);
	}

	public de.uni_koblenz.jgralab.demo.schema.Inheritance getNextInheritanceIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralab.demo.schema.Inheritance)getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Inheritance.EC, orientation);
	}
	public Node getAlpha() {
		return (Node) super.getAlpha();
	}
	public Node getOmega() {
		return (Node) super.getOmega();
	}
}
