/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.emf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.incquery.patternlanguage.emf.services.EMFPatternLanguageGrammarAccess;

public class EMFPatternLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EMFPatternLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.incquery.patternlanguage.emf.parser.antlr.internal.InternalEMFPatternLanguageParser createParser(XtextTokenStream stream) {
		return new org.eclipse.incquery.patternlanguage.emf.parser.antlr.internal.InternalEMFPatternLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EMFPatternModel";
	}
	
	public EMFPatternLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EMFPatternLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
