/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema.impl.std;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

import de.uni_koblenz.jgralab.ImplementationType;

import de.uni_koblenz.jgralab.demo.schema.GraphModelFactory;

public class GraphModelFactoryImpl extends GraphFactoryImpl implements GraphModelFactory {

	public GraphModelFactoryImpl() {
		super(de.uni_koblenz.jgralab.demo.schema.GraphSchema.instance(), ImplementationType.STANDARD);
		createMaps();
		setGraphImplementationClass(de.uni_koblenz.jgralab.demo.schema.GraphModel.GC, de.uni_koblenz.jgralab.demo.schema.impl.std.GraphModelImpl.class);
		setVertexImplementationClass(de.uni_koblenz.jgralab.demo.schema.Node.VC, de.uni_koblenz.jgralab.demo.schema.impl.std.NodeImpl.class);
		setEdgeImplementationClass(de.uni_koblenz.jgralab.demo.schema.Connection.EC, de.uni_koblenz.jgralab.demo.schema.impl.std.ConnectionImpl.class);
	}
}
