<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smell_model" nsURI="http://smell_model/1.0" nsPrefix="smell_model">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell_Rolemapping_Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell" lowerBound="1"
        eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleMapping" lowerBound="1"
        upperBound="-1" eType="ecore:EClass rolemapping.ecore#//RoleMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingConcretisation"
        upperBound="-1" eType="#//MappingConcretisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelSpecification"
        lowerBound="1" eType="ecore:EClass Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality_ModelSmell_Mapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell" lowerBound="1"
        eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" lowerBound="1"
        eType="#//Quality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true" interface="true">
    <eOperations name="calculate">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        <eTypeArguments eClassifier="ecore:EDataType Ecore.ecore#//EFloatObject"/>
      </eGenericType>
      <eParameters name="loadedModel" eType="ecore:EDataType Ecore.ecore#//EResource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric_Quality_Mapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" lowerBound="1"
        eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
        eType="#//Metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmellModel">
    <eOperations name="init"/>
    <eOperations name="calculate"/>
    <eOperations name="register">
      <eParameters name="o" eType="#//Observer"/>
    </eOperations>
    <eOperations name="unregister">
      <eParameters name="o" eType="#//Observer"/>
    </eOperations>
    <eOperations name="inform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell_roleMapping"
        lowerBound="1" upperBound="-1" eType="#//ModelSmell_Rolemapping_Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality_modelSmell" lowerBound="1"
        upperBound="-1" eType="#//Quality_ModelSmell_Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric_quality" lowerBound="1"
        upperBound="-1" eType="#//Metric_Quality_Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualities" lowerBound="1"
        upperBound="-1" eType="#//Quality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmells" lowerBound="1"
        upperBound="-1" eType="#//ModelSmell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" lowerBound="1"
        upperBound="-1" eType="#//Metric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configStrings" transient="true"
        defaultValueLiteral="">
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EDataType Ecore.ecore#//EString"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadedResourcePath" eType="ecore:EDataType Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualityScale" transient="true"
        defaultValueLiteral="">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType Ecore.ecore#//EMap">
        <eTypeArguments eClassifier="#//Quality"/>
        <eTypeArguments eClassifier="ecore:EDataType Ecore.ecore#//EFloatObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType Ecore.ecore#//EFloatObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingConcretisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newFactor" eType="ecore:EDataType Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//Mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observer" abstract="true" interface="true">
    <eOperations name="update"/>
  </eClassifiers>
</ecore:EPackage>
