/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package dk.itu.sdg.language.xwpf.resource.xwpf.grammar;

public class XwpfGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static XwpfGrammarInformationProvider INSTANCE = new XwpfGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_0_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Content", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_0_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_0_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getContent().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.CONTENT__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_0_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_0_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_0_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_0_0_0_2_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_0_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_0_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_0_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_0_0_0_0, XWPF_0_0_0_1, XWPF_0_0_0_2, XWPF_0_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getContent(), XWPF_0_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Document", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("bodyElements", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__BODY_ELEMENTS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getBodyElement(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_0_0, XWPF_1_0_0_2_0_0_1, XWPF_1_0_0_2_0_0_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("comments", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_1_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_1_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__COMMENTS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getComment(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_1_0, XWPF_1_0_0_2_0_1_1, XWPF_1_0_0_2_0_1_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("endnotes", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_2_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_2_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__ENDNOTES), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFootnote(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_2_0, XWPF_1_0_0_2_0_2_1, XWPF_1_0_0_2_0_2_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_3_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("footers", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_3_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_3_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__FOOTERS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFooter(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_3_0, XWPF_1_0_0_2_0_3_1, XWPF_1_0_0_2_0_3_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_4_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("footnotes", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_4_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_4_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__FOOTNOTES), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFootnote(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_4 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_4_0, XWPF_1_0_0_2_0_4_1, XWPF_1_0_0_2_0_4_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_5_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("headers", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_5_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_5_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__HEADERS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHeader(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_5 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_5_0, XWPF_1_0_0_2_0_5_1, XWPF_1_0_0_2_0_5_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_6_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("hyperlinks", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_6_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_6_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__HYPERLINKS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHyperlink(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_6 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_6_0, XWPF_1_0_0_2_0_6_1, XWPF_1_0_0_2_0_6_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_7_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("numbering", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_7_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_7_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__NUMBERING), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getNumbering(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_7 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_7_0, XWPF_1_0_0_2_0_7_1, XWPF_1_0_0_2_0_7_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_8_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("packagePictures", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_8_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_8_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__PACKAGE_PICTURES), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getPictureData(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_8 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_8_0, XWPF_1_0_0_2_0_8_1, XWPF_1_0_0_2_0_8_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_9_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("paragraphs", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_9_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_9_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__PARAGRAPHS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_9 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_9_0, XWPF_1_0_0_2_0_9_1, XWPF_1_0_0_2_0_9_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_10_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("pictures", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_10_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_10_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__PICTURES), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getPictureData(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_10 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_10_0, XWPF_1_0_0_2_0_10_1, XWPF_1_0_0_2_0_10_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal XWPF_1_0_0_2_0_11_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__STYLES), new String[] {"unrecognized", "unrecognized", "heading1", "Heading1", "heading2", "Heading2", "listParagraph", "ListParagraph", "normal", "null", }, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_11 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_11_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_12_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("tables", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_2_0_12_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_1_0_0_2_0_12_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.DOCUMENT__TABLES), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getTable(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0_2_0_12 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_12_0, XWPF_1_0_0_2_0_12_1, XWPF_1_0_0_2_0_12_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_1_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_2_0_0, XWPF_1_0_0_2_0_1, XWPF_1_0_0_2_0_2, XWPF_1_0_0_2_0_3, XWPF_1_0_0_2_0_4, XWPF_1_0_0_2_0_5, XWPF_1_0_0_2_0_6, XWPF_1_0_0_2_0_7, XWPF_1_0_0_2_0_8, XWPF_1_0_0_2_0_9, XWPF_1_0_0_2_0_10, XWPF_1_0_0_2_0_11, XWPF_1_0_0_2_0_12);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_1_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_1_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_1_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_1_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0_0, XWPF_1_0_0_1, XWPF_1_0_0_2, XWPF_1_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_1_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getDocument(), XWPF_1_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("BodyElement", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_2_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_2_0_0_0, XWPF_2_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_2_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getBodyElement(), XWPF_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_3_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Comment", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_3_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_3_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getComment().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.COMMENT__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_3_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_3_0_0_2_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getComment().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.COMMENT__AUTHOR), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_3_0_0_2_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0_2_0_1_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_3_0_0_2_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getComment().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.COMMENT__IDENTIFIER), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_3_0_0_2_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0_2_0_2_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_3_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0_2_0_0, XWPF_3_0_0_2_0_1, XWPF_3_0_0_2_0_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_3_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_3_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_3_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_3_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0_0, XWPF_3_0_0_1, XWPF_3_0_0_2, XWPF_3_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_3_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_3_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getComment(), XWPF_3_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_4_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Footnote", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_4_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_4_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFootnote().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.FOOTNOTE__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_4_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_4_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_4_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_4_0_0_2_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_4_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_4_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_4_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_4_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_4_0_0_0, XWPF_4_0_0_1, XWPF_4_0_0_2, XWPF_4_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_4_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_4_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_4 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFootnote(), XWPF_4_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_5_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Footer", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_5_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_5_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFooter().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.FOOTER__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_5_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_5_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_5_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_5_0_0_2_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_5_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_5_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_5_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_5_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_5_0_0_0, XWPF_5_0_0_1, XWPF_5_0_0_2, XWPF_5_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_5_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_5_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_5 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getFooter(), XWPF_5_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_6_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Header", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_6_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_6_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHeader().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.HEADER__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_6_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_6_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_6_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_6_0_0_2_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_6_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_6_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_6_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_6_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_6_0_0_0, XWPF_6_0_0_1, XWPF_6_0_0_2, XWPF_6_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_6_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_6_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_6 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHeader(), XWPF_6_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_7_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Hyperlink", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_7_0_0_1_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHyperlink().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.HYPERLINK__IDENTIFIER), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_7_0_0_1_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_7_0_0_1_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_7_0_0_1_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHyperlink().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.HYPERLINK__URL), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_7_0_0_1_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_7_0_0_1_0_1_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_7_0_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_7_0_0_1_0_0, XWPF_7_0_0_1_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_7_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_7_0_0_1_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_7_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_7_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_7_0_0_0, XWPF_7_0_0_1, XWPF_7_0_0_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_7_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_7_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_7 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getHyperlink(), XWPF_7_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_8_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Numbering", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_8_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_8_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_8_0_0_0, XWPF_8_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_8_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_8_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_8 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getNumbering(), XWPF_8_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_9_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("PictureData", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_9_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_9_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_9_0_0_0, XWPF_9_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_9_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_9_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_9 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getPictureData(), XWPF_9_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Paragraph", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("runs", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_1_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_10_0_0_2_0_1_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__RUNS), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_1_0, XWPF_10_0_0_2_0_1_1, XWPF_10_0_0_2_0_1_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("part", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_2_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_10_0_0_2_0_2_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__PART), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getPart(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_2_0, XWPF_10_0_0_2_0_2_1, XWPF_10_0_0_2_0_2_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_3_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("body", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_2_0_3_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(":", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment XWPF_10_0_0_2_0_3_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfContainment(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BODY), dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getBody(), }, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_3_0, XWPF_10_0_0_2_0_3_1, XWPF_10_0_0_2_0_3_2);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_4_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__ALIGNMENT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_4 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_4_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_5_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BORDER_BOTTOM), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_5 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_5_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_6_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BORDER_TOP), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_6 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_6_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_7_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BORDER_BETWEEN), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_7 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_7_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_8_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BORDER_LEFT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_8 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_8_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_9_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__BORDER_RIGHT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_9 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_9_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_10_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__VERTICAL_ALIGNMENT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_10 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_10_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_11_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__FOOTNOTE_TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_11 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_11_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_12_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__INDENT_FST_LINE), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_12 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_12_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_13_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__INDENT_HANGING), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_13 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_13_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_14_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__INDENT_LEFT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_14 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_14_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_15_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__INDENT_RIGHT), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_15 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_15_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_16_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__SPACING_AFTER), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_16 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_16_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_17_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__SPACING_AFTER_LINES), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_17 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_17_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_18_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__SPACING_BEFORE), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_18 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_18_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_19_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__SPACING_BEFORE_LINES), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_19 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_19_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_10_0_0_2_0_20_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__SPACING_LINE_RULE), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_20 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_20_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal XWPF_10_0_0_2_0_21_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.PARAGRAPH__STYLE), new String[] {"unrecognized", "unrecognized", "heading1", "Heading1", "heading2", "Heading2", "listParagraph", "ListParagraph", "normal", "null", }, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0_2_0_21 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_21_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_10_0_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_2_0_0, XWPF_10_0_0_2_0_1, XWPF_10_0_0_2_0_2, XWPF_10_0_0_2_0_3, XWPF_10_0_0_2_0_4, XWPF_10_0_0_2_0_5, XWPF_10_0_0_2_0_6, XWPF_10_0_0_2_0_7, XWPF_10_0_0_2_0_8, XWPF_10_0_0_2_0_9, XWPF_10_0_0_2_0_10, XWPF_10_0_0_2_0_11, XWPF_10_0_0_2_0_12, XWPF_10_0_0_2_0_13, XWPF_10_0_0_2_0_14, XWPF_10_0_0_2_0_15, XWPF_10_0_0_2_0_16, XWPF_10_0_0_2_0_17, XWPF_10_0_0_2_0_18, XWPF_10_0_0_2_0_19, XWPF_10_0_0_2_0_20, XWPF_10_0_0_2_0_21);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_10_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_10_0_0_2_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_10_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_10_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0_0, XWPF_10_0_0_1, XWPF_10_0_0_2, XWPF_10_0_0_3);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_10_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_10_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_10 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getParagraph(), XWPF_10_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_11_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Table", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_11_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_11_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_11_0_0_0, XWPF_11_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_11_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_11_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_11 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getTable(), XWPF_11_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal XWPF_12_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__IS_BOLD), "isBold", "", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal XWPF_12_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__IS_ITALIC), "isItalic", "", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal XWPF_12_0_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__IS_STRIKE), "isStrike", "", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_12_0_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Run", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_12_0_0_4 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("{", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_12_0_0_5_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__TEXT), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0_5_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_12_0_0_5_0_1_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__FONT_FAMILY), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0_5_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_1_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_12_0_0_5_0_2_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__FONT_SIZE), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0_5_0_2 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_2_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_12_0_0_5_0_3_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__COLOR), "QUOTED_34_34", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0_5_0_3 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_3_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder XWPF_12_0_0_5_0_4_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfPlaceholder(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun().getEStructuralFeature(dk.itu.sdg.language.xwpf.XwpfPackage.RUN__TEXT_POSITION), "TEXT", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, 0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0_5_0_4 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_4_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_12_0_0_5_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_5_0_0, XWPF_12_0_0_5_0_1, XWPF_12_0_0_5_0_2, XWPF_12_0_0_5_0_3, XWPF_12_0_0_5_0_4);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound XWPF_12_0_0_5 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCompound(XWPF_12_0_0_5_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.STAR);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_12_0_0_6 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("}", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_12_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0_0, XWPF_12_0_0_1, XWPF_12_0_0_2, XWPF_12_0_0_3, XWPF_12_0_0_4, XWPF_12_0_0_5, XWPF_12_0_0_6);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_12_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_12_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_12 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getRun(), XWPF_12_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_13_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Part", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_13_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_13_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_13_0_0_0, XWPF_13_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_13_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_13_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_13 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getPart(), XWPF_13_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_14_0_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword("Body", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword XWPF_14_0_0_1 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword(";", dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence XWPF_14_0_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSequence(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_14_0_0_0, XWPF_14_0_0_1);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice XWPF_14_0 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfChoice(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE, XWPF_14_0_0);
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule XWPF_14 = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule(dk.itu.sdg.language.xwpf.XwpfPackage.eINSTANCE.getBody(), XWPF_14_0, dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfCardinality.ONE);
	
	public static String getSyntaxElementID(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSyntaxElement) dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule[] RULES = new dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule[] {
		XWPF_0,
		XWPF_1,
		XWPF_2,
		XWPF_3,
		XWPF_4,
		XWPF_5,
		XWPF_6,
		XWPF_7,
		XWPF_8,
		XWPF_9,
		XWPF_10,
		XWPF_11,
		XWPF_12,
		XWPF_13,
		XWPF_14,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword) {
			keywords.add(((dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfKeyword) element).getValue());
		} else if (element instanceof dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal) {
			keywords.add(((dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal) element).getTrueLiteral());
			keywords.add(((dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal) {
			dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal terminal = (dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (dk.itu.sdg.language.xwpf.resource.xwpf.grammar.XwpfSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
