<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smell_model" nsURI="http://smell_model/1.0" nsPrefix="smell_model">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell_Rolemapping_Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell" lowerBound="1"
        eType="#//ModelSmell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality_ModelSmell_Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell" lowerBound="1"
        eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualities" lowerBound="1"
        upperBound="-1" eType="#//Quality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true">
    <eOperations name="calculate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric_Quality_Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" lowerBound="1"
        eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" lowerBound="1"
        upperBound="-1" eType="#//Metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eOperations name="init"/>
    <eOperations name="createModelSmell_Rolemapping_Mapping"/>
    <eOperations name="createQuality_ModelSmell_Mapping"/>
    <eOperations name="createMetric_Quality_Mapping"/>
    <eOperations name="calculate"/>
    <eOperations name="updateGui"/>
    <eOperations name="refactor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmell_roleMapping"
        lowerBound="1" upperBound="-1" eType="#//ModelSmell_Rolemapping_Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality_modelSmell" lowerBound="1"
        upperBound="-1" eType="#//Quality_ModelSmell_Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric_quality" lowerBound="1"
        upperBound="-1" eType="#//Metric_Quality_Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gui" lowerBound="1" eType="#//GUI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualities" lowerBound="1"
        upperBound="-1" eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSmells" lowerBound="1"
        upperBound="-1" eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" lowerBound="1"
        upperBound="-1" eType="#//Metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GUI">
    <eOperations name="notifyComponents"/>
    <eOperations name="add"/>
    <eOperations name="remove"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Observer">
    <eOperations name="update"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observer" abstract="true" interface="true">
    <eOperations name="update"/>
  </eClassifiers>
</ecore:EPackage>
