<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smell_model"
    nsURI="http://smell_model/1.0" nsPrefix="smell_model">
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSmell_Rolemapping_Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModelSmell has" lowerBound="1"
        eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quality_ModelSmell_Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Quality_ModelSmell_Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//ModelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        upperBound="-1" eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualities" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelSmell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eOperations name="calculate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric_Quality_Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        eType="#//Quality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" lowerBound="1"
        upperBound="-1" eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metrics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
