/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.emf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EMFPatternLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/incquery/patternlanguage/emf/parser/antlr/internal/InternalEMFPatternLanguage.tokens");
	}
}
