/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema;

import de.uni_koblenz.jgralab.GraphFactory;

public interface GraphModelFactory extends GraphFactory {
}
