/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema;

public interface GraphModel extends de.uni_koblenz.jgralab.Graph {

	public static final de.uni_koblenz.jgralab.schema.GraphClass GC = de.uni_koblenz.jgralab.demo.schema.GraphSchema.instance().getGraphClass();

	// ------------------------ Code for Connection ------------------------

	/**
	 * @return the first Connection edge in this graph
	 */
	public de.uni_koblenz.jgralab.demo.schema.Connection getFirstConnection();

	/**
	 * Creates a new Connection edge in this graph.
	 *
	 * @param alpha the start vertex of the edge
	 * @param omega the target vertex of the edge
	*/
	public de.uni_koblenz.jgralab.demo.schema.Connection createConnection(de.uni_koblenz.jgralab.demo.schema.Node alpha, de.uni_koblenz.jgralab.demo.schema.Node omega);

	// ------------------------ Code for Node ------------------------

	/**
	 * @return the first Node vertex in this graph
	 */
	public de.uni_koblenz.jgralab.demo.schema.Node getFirstNode();

	/**
	 * Creates a new Node vertex in this graph.
	 *
	*/
	public de.uni_koblenz.jgralab.demo.schema.Node createNode();

	/**
	 * @return an Iterable for all edges of this graph that are of type Connection or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Connection> getConnectionEdges();
	

	/**
	 * @return an Iterable for all vertices of this graph that are of type Node or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Node> getNodeVertices();
	
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Node> getNodeVertices(de.uni_koblenz.jgralab.VertexFilter<de.uni_koblenz.jgralab.demo.schema.Node> filter);
	
}
