/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.emftext.language.refactoring.specification.resource.grammar;

public class RefspecGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public static class Rule extends org.emftext.language.refactoring.specification.resource.grammar.RefspecSyntaxElement {
		
		private final org.eclipse.emf.ecore.EClass metaclass;
		
		public Rule(org.eclipse.emf.ecore.EClass metaclass, org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice choice, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality cardinality) {
			super(cardinality, new org.emftext.language.refactoring.specification.resource.grammar.RefspecSyntaxElement[] {choice});
			this.metaclass = metaclass;
		}
		
		public org.eclipse.emf.ecore.EClass getMetaclass() {
			return metaclass;
		}
		
		public org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice getDefinition() {
			return (org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice) getChildren()[0];
		}
	}
	
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("REFACTORING", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_0_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_0_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRefactoringSpecification().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.REFACTORING_SPECIFICATION__NAME), "UPPER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("FOR", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_0_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_0_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRefactoringSpecification().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.REFACTORING_SPECIFICATION__USED_ROLE_MODEL), "QUOTED_60_62", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_7 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_8 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_9 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("STEPS", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_10 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("{", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_11 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 1);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_0_0_0_12_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRefactoringSpecification().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.REFACTORING_SPECIFICATION__INSTRUCTIONS), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_12_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(";", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_12_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_0_0_0_12_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_0_0_0_12_0_0_0, REFSPEC_0_0_0_12_0_0_1, REFSPEC_0_0_0_12_0_0_2);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_0_0_0_12_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_0_0_0_12_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound REFSPEC_0_0_0_12 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound(REFSPEC_0_0_0_12_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.PLUS);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak REFSPEC_0_0_0_13 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecLineBreak(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, 0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_0_0_0_14 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("}", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_0_0_0_0, REFSPEC_0_0_0_1, REFSPEC_0_0_0_2, REFSPEC_0_0_0_3, REFSPEC_0_0_0_4, REFSPEC_0_0_0_5, REFSPEC_0_0_0_6, REFSPEC_0_0_0_7, REFSPEC_0_0_0_8, REFSPEC_0_0_0_9, REFSPEC_0_0_0_10, REFSPEC_0_0_0_11, REFSPEC_0_0_0_12, REFSPEC_0_0_0_13, REFSPEC_0_0_0_14);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_0_0_0);
	public final static Rule REFSPEC_0 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRefactoringSpecification(), REFSPEC_0_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_1_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("create", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_1_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("new", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_1_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getCREATE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CREATE__VARIABLE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_1_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(":", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_7 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_1_0_0_8 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getCREATE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CREATE__SOURCE_ROLE), "UPPER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_9 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_1_0_0_10 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("in", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_1_0_0_11 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_1_0_0_12 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getCREATE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CREATE__TARGET_CONTEXT), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_1_0_0_13_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("at", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_1_0_0_13_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getCREATE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CREATE__INDEX), "LOWER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_1_0_0_13_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_1_0_0_13_0_0_0, REFSPEC_1_0_0_13_0_0_1);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_1_0_0_13_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_1_0_0_13_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound REFSPEC_1_0_0_13 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound(REFSPEC_1_0_0_13_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.QUESTIONMARK);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_1_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_1_0_0_0, REFSPEC_1_0_0_1, REFSPEC_1_0_0_2, REFSPEC_1_0_0_3, REFSPEC_1_0_0_4, REFSPEC_1_0_0_5, REFSPEC_1_0_0_6, REFSPEC_1_0_0_7, REFSPEC_1_0_0_8, REFSPEC_1_0_0_9, REFSPEC_1_0_0_10, REFSPEC_1_0_0_11, REFSPEC_1_0_0_12, REFSPEC_1_0_0_13);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_1_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_1_0_0);
	public final static Rule REFSPEC_1 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getCREATE(), REFSPEC_1_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_2_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("move", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_2_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_2_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getMOVE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.MOVE__SOURCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_2_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_2_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("to", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_2_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_2_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getMOVE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.MOVE__TARGET), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_2_0_0_7_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("at", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_2_0_0_7_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getMOVE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.MOVE__INDEX), "LOWER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_2_0_0_7_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_2_0_0_7_0_0_0, REFSPEC_2_0_0_7_0_0_1);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_2_0_0_7_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_2_0_0_7_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound REFSPEC_2_0_0_7 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound(REFSPEC_2_0_0_7_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.QUESTIONMARK);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_2_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_2_0_0_0, REFSPEC_2_0_0_1, REFSPEC_2_0_0_2, REFSPEC_2_0_0_3, REFSPEC_2_0_0_4, REFSPEC_2_0_0_5, REFSPEC_2_0_0_6, REFSPEC_2_0_0_7);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_2_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_2_0_0);
	public final static Rule REFSPEC_2 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getMOVE(), REFSPEC_2_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_3_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("set", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_3_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_3_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("use", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_3_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_3_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("of", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_3_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_3_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getSET().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.SET__SOURCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_3_0_0_7 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_3_0_0_8 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("in", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_3_0_0_9 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_3_0_0_10 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getSET().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.SET__TARGET), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_3_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_3_0_0_0, REFSPEC_3_0_0_1, REFSPEC_3_0_0_2, REFSPEC_3_0_0_3, REFSPEC_3_0_0_4, REFSPEC_3_0_0_5, REFSPEC_3_0_0_6, REFSPEC_3_0_0_7, REFSPEC_3_0_0_8, REFSPEC_3_0_0_9, REFSPEC_3_0_0_10);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_3_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_3_0_0);
	public final static Rule REFSPEC_3 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getSET(), REFSPEC_3_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_4_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("assign", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_4_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_4_0_0_2_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getASSIGN().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.ASSIGN__SOURCE_ATTRIBUTE), "DOT_NOTATION", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_4_0_0_2_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_4_0_0_2_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("for", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_4_0_0_2_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_4_0_0_2_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0_2_0_0_0, REFSPEC_4_0_0_2_0_0_1, REFSPEC_4_0_0_2_0_0_2, REFSPEC_4_0_0_2_0_0_3);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_4_0_0_2_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0_2_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound REFSPEC_4_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound(REFSPEC_4_0_0_2_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.QUESTIONMARK);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_4_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getASSIGN().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.ASSIGN__TARGET_ATTRIBUTE), "DOT_NOTATION", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_4_0_0_4_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("and", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_4_0_0_4_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_4_0_0_4_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getASSIGN().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.ASSIGN__ADDITIONAL_COMMAND), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_4_0_0_4_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0_4_0_0_0, REFSPEC_4_0_0_4_0_0_1, REFSPEC_4_0_0_4_0_0_2);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_4_0_0_4_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0_4_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound REFSPEC_4_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecCompound(REFSPEC_4_0_0_4_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.QUESTIONMARK);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_4_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0_0, REFSPEC_4_0_0_1, REFSPEC_4_0_0_2, REFSPEC_4_0_0_3, REFSPEC_4_0_0_4);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_4_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_4_0_0);
	public final static Rule REFSPEC_4 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getASSIGN(), REFSPEC_4_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_5_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("update", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_5_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_5_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_5_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_5_0_0);
	public final static Rule REFSPEC_5 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getUPDATE(), REFSPEC_5_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_6_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariable().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.VARIABLE__NAME), "LOWER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_6_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_6_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_6_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_6_0_0);
	public final static Rule REFSPEC_6 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariable(), REFSPEC_6_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_7_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariableReference().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.VARIABLE_REFERENCE__VARIABLE), "LOWER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_7_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_7_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_7_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_7_0_0);
	public final static Rule REFSPEC_7 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariableReference(), REFSPEC_7_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_8_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("object", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_8_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariableAssignment().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.VARIABLE_ASSIGNMENT__VARIABLE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_8_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(":=", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_8_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariableAssignment().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.VARIABLE_ASSIGNMENT__ASSIGNMENT), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_8_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_8_0_0_0, REFSPEC_8_0_0_1, REFSPEC_8_0_0_2, REFSPEC_8_0_0_3);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_8_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_8_0_0);
	public final static Rule REFSPEC_8 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getVariableAssignment(), REFSPEC_8_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_9_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRoleReference().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.ROLE_REFERENCE__ROLE), "UPPER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_9_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_9_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("from", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_9_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(1, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_9_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRoleReference().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.ROLE_REFERENCE__FROM), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_9_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_9_0_0_0, REFSPEC_9_0_0_1, REFSPEC_9_0_0_2, REFSPEC_9_0_0_3, REFSPEC_9_0_0_4);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_9_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_9_0_0);
	public final static Rule REFSPEC_9 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRoleReference(), REFSPEC_9_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_10_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getTRACE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.TRACE__ROLE), "UPPER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_10_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("as", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_10_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("trace", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_10_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("(", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_10_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getTRACE().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.TRACE__REFERENCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_10_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(")", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_10_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_10_0_0_0, REFSPEC_10_0_0_1, REFSPEC_10_0_0_2, REFSPEC_10_0_0_3, REFSPEC_10_0_0_4, REFSPEC_10_0_0_5);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_10_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_10_0_0);
	public final static Rule REFSPEC_10 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getTRACE(), REFSPEC_10_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_11_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRelationReference().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.RELATION_REFERENCE__RELATION), "DOT_NOTATION", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_11_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_11_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_11_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_11_0_0);
	public final static Rule REFSPEC_11 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getRelationReference(), REFSPEC_11_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_12_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getConstantsReference().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CONSTANTS_REFERENCE__REFERENCED_CONSTANT), "CONSTANTS", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_12_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_12_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_12_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_12_0_0);
	public final static Rule REFSPEC_12 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getConstantsReference(), REFSPEC_12_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_13_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFromClause().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.FROM_CLAUSE__OPERATOR), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace REFSPEC_13_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecWhiteSpace(0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_13_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("(", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_13_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFromClause().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.FROM_CLAUSE__REFERENCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_13_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(")", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_13_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_13_0_0_0, REFSPEC_13_0_0_1, REFSPEC_13_0_0_2, REFSPEC_13_0_0_3, REFSPEC_13_0_0_4);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_13_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_13_0_0);
	public final static Rule REFSPEC_13 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFromClause(), REFSPEC_13_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_14_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("uptree", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_14_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_14_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_14_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_14_0_0);
	public final static Rule REFSPEC_14 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getUPTREE(), REFSPEC_14_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_15_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("path", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_15_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_15_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_15_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_15_0_0);
	public final static Rule REFSPEC_15 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getPATH(), REFSPEC_15_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_16_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("index", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_16_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFIRST().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.FIRST__VARIABLE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_16_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(":=", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_16_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("first", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_16_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("(", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_16_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFIRST().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.FIRST__REFERENCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_16_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(")", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_16_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_16_0_0_0, REFSPEC_16_0_0_1, REFSPEC_16_0_0_2, REFSPEC_16_0_0_3, REFSPEC_16_0_0_4, REFSPEC_16_0_0_5, REFSPEC_16_0_0_6);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_16_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_16_0_0);
	public final static Rule REFSPEC_16 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getFIRST(), REFSPEC_16_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_17_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("index", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_17_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getLAST().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.LAST__VARIABLE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_17_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(":=", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_17_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("last", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_17_0_0_4 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("(", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_17_0_0_5 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getLAST().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.LAST__REFERENCE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_17_0_0_6 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(")", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_17_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_17_0_0_0, REFSPEC_17_0_0_1, REFSPEC_17_0_0_2, REFSPEC_17_0_0_3, REFSPEC_17_0_0_4, REFSPEC_17_0_0_5, REFSPEC_17_0_0_6);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_17_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_17_0_0);
	public final static Rule REFSPEC_17 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getLAST(), REFSPEC_17_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_18_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword("index", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment REFSPEC_18_0_0_1 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecContainment(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getConcreteIndex().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CONCRETE_INDEX__VARIABLE), org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword REFSPEC_18_0_0_2 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecKeyword(":=", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_18_0_0_3 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getConcreteIndex().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.CONCRETE_INDEX__INDEX), "INTEGER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_18_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_18_0_0_0, REFSPEC_18_0_0_1, REFSPEC_18_0_0_2, REFSPEC_18_0_0_3);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_18_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_18_0_0);
	public final static Rule REFSPEC_18 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getConcreteIndex(), REFSPEC_18_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder REFSPEC_19_0_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecPlaceholder(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getIndexVariable().getEStructuralFeature(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.INDEX_VARIABLE__NAME), "LOWER_IDENTIFIER", org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence REFSPEC_19_0_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecSequence(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_19_0_0_0);
	public final static org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice REFSPEC_19_0 = new org.emftext.language.refactoring.specification.resource.grammar.RefspecChoice(org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE, REFSPEC_19_0_0);
	public final static Rule REFSPEC_19 = new Rule(org.emftext.language.refactoring.refactoring_specification.RefactoringSpecificationPackage.eINSTANCE.getIndexVariable(), REFSPEC_19_0, org.emftext.language.refactoring.specification.resource.grammar.RefspecCardinality.ONE);
}
