/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema.impl.std;

import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.impl.std.VertexImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.exception.GraphIOException;
import de.uni_koblenz.jgralab.exception.NoSuchAttributeException;

import java.io.IOException;

public class NodeImpl extends VertexImpl implements de.uni_koblenz.jgralab.demo.schema.Node, de.uni_koblenz.jgralab.Vertex {

	protected java.lang.String _name;

	public NodeImpl(int id, de.uni_koblenz.jgralab.Graph g) {
		super(id, g);
	}

	@Override
	public final de.uni_koblenz.jgralab.schema.VertexClass getAttributedElementClass() {
		return de.uni_koblenz.jgralab.demo.schema.Node.VC;
	}

	@Override
	public final java.lang.Class<? extends de.uni_koblenz.jgralab.Vertex> getSchemaClass() {
		return de.uni_koblenz.jgralab.demo.schema.Node.class;
	}

	@SuppressWarnings("unchecked")
	public <T> T getAttribute(String attributeName) {
		if (attributeName.equals("name")) return (T) get_name();
		throw new NoSuchAttributeException("Node doesn't contain an attribute " + attributeName);
	}

	public <T> void setAttribute(String attributeName, T data) {
		if (attributeName.equals("name")) {
			set_name((java.lang.String) data);
			return;
		}
		throw new NoSuchAttributeException("Node doesn't contain an attribute " + attributeName);
	}

	public java.lang.String get_name() {
		return _name;
	}

	public void set_name(java.lang.String _name) {
		ecaAttributeChanging("name", this._name, _name);
		Object oldValue = this._name;
		this._name = _name;
		graphModified();
		ecaAttributeChanged("name", oldValue, _name);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		_name = io.matchUtfString();
		set_name(_name);
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException {
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_name = io.matchUtfString();
			set_name(_name);
			return;
		}
		throw new NoSuchAttributeException("Node doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		io.space();
		io.writeUtfString(_name);
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException {
		if (attributeName.equals("name")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeUtfString(_name);
			return io.getStringWriterResult();
		}
		throw new NoSuchAttributeException("Node doesn't contain an attribute " + attributeName);
	}

	@Override
	public de.uni_koblenz.jgralab.demo.schema.Node getNextNode() {
		return (de.uni_koblenz.jgralab.demo.schema.Node)getNextVertex(de.uni_koblenz.jgralab.demo.schema.Node.VC);
	}

	@Override
	public de.uni_koblenz.jgralab.demo.schema.Connection getFirstConnectionIncidence() {
		return (de.uni_koblenz.jgralab.demo.schema.Connection)getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC);
	}

	@Override
	public de.uni_koblenz.jgralab.demo.schema.Connection getFirstConnectionIncidence(EdgeDirection orientation) {
		return (de.uni_koblenz.jgralab.demo.schema.Connection)getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, orientation);
	}
		@Override
		public de.uni_koblenz.jgralab.demo.schema.Connection add_source(de.uni_koblenz.jgralab.demo.schema.Node vertex) {
			return ((de.uni_koblenz.jgralab.demo.schema.GraphModel)getGraph()).createEdge(de.uni_koblenz.jgralab.demo.schema.Connection.EC, (de.uni_koblenz.jgralab.demo.schema.Node) vertex, (de.uni_koblenz.jgralab.demo.schema.Node) this);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.jgralab.demo.schema.Node> remove_source() {
			java.util.List<de.uni_koblenz.jgralab.demo.schema.Node> adjacences = new java.util.ArrayList<de.uni_koblenz.jgralab.demo.schema.Node>();
			de.uni_koblenz.jgralab.demo.schema.Connection edge = (de.uni_koblenz.jgralab.demo.schema.Connection) getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.jgralab.demo.schema.Connection next = (de.uni_koblenz.jgralab.demo.schema.Connection) edge.getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN);
				adjacences.add((de.uni_koblenz.jgralab.demo.schema.Node) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_source(de.uni_koblenz.jgralab.demo.schema.Node vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.jgralab.demo.schema.Connection edge = (de.uni_koblenz.jgralab.demo.schema.Connection) getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.jgralab.demo.schema.Connection next = (de.uni_koblenz.jgralab.demo.schema.Connection) edge.getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_source() {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.jgralab.demo.schema.Connection, V>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN, null);
		}
		
		@Override
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_source(de.uni_koblenz.jgralab.VertexFilter<V> filter) {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.jgralab.demo.schema.Connection, V>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.IN, filter);
		}
		@Override
		public de.uni_koblenz.jgralab.demo.schema.Connection add_target(de.uni_koblenz.jgralab.demo.schema.Node vertex) {
			return ((de.uni_koblenz.jgralab.demo.schema.GraphModel)getGraph()).createEdge(de.uni_koblenz.jgralab.demo.schema.Connection.EC, (de.uni_koblenz.jgralab.demo.schema.Node) this, (de.uni_koblenz.jgralab.demo.schema.Node) vertex);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.jgralab.demo.schema.Node> remove_target() {
			java.util.List<de.uni_koblenz.jgralab.demo.schema.Node> adjacences = new java.util.ArrayList<de.uni_koblenz.jgralab.demo.schema.Node>();
			de.uni_koblenz.jgralab.demo.schema.Connection edge = (de.uni_koblenz.jgralab.demo.schema.Connection) getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.jgralab.demo.schema.Connection next = (de.uni_koblenz.jgralab.demo.schema.Connection) edge.getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT);
				adjacences.add((de.uni_koblenz.jgralab.demo.schema.Node) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_target(de.uni_koblenz.jgralab.demo.schema.Node vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.jgralab.demo.schema.Connection edge = (de.uni_koblenz.jgralab.demo.schema.Connection) getFirstIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.jgralab.demo.schema.Connection next = (de.uni_koblenz.jgralab.demo.schema.Connection) edge.getNextIncidence(de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_target() {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.jgralab.demo.schema.Connection, V>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT, null);
		}
		
		@Override
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_target(de.uni_koblenz.jgralab.VertexFilter<V> filter) {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.jgralab.demo.schema.Connection, V>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC, EdgeDirection.OUT, filter);
		}

	@Override
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Connection> getConnectionIncidences() {
		return new IncidenceIterable<de.uni_koblenz.jgralab.demo.schema.Connection>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC);
	}
	
	@Override
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Connection> getConnectionIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.jgralab.demo.schema.Connection>(this, de.uni_koblenz.jgralab.demo.schema.Connection.EC, direction);
	}
}
