/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.jgralab.demo.schema;

import de.uni_koblenz.jgralab.EdgeDirection;

public interface Node extends de.uni_koblenz.jgralab.Vertex {

	public static final de.uni_koblenz.jgralab.schema.VertexClass VC = de.uni_koblenz.jgralab.demo.schema.GraphSchema.instance().getGraphClass().getVertexClass("Node");

	public java.lang.String get_name();

	public void set_name(java.lang.String _name);

	/**
	 * @return the next de.uni_koblenz.jgralab.demo.schema.Node vertex in the global vertex sequence
	 */
	public de.uni_koblenz.jgralab.demo.schema.Node getNextNode();

	/**
	 * @return the first edge of class Connection at this vertex
	 */
	public de.uni_koblenz.jgralab.demo.schema.Connection getFirstConnectionIncidence();

	/**
	 * @return the first edge of class Connection at this vertex
	 * @param orientation the orientation of the edge
	 */
	public de.uni_koblenz.jgralab.demo.schema.Connection getFirstConnectionIncidence(EdgeDirection orientation);
		/**
		 * adds the given vertex as <code>source</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.demo.schema.Connection</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.demo.schema.Connection add_source(de.uni_koblenz.jgralab.demo.schema.Node vertex);
		/**
		 * removes all source adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.demo.schema.Node> remove_source();
		/**
		 * removes the given vertex as <code>source</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_source(de.uni_koblenz.jgralab.demo.schema.Node vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'source'
		 *         (connected with a <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge).
		 */
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_source();
		
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_source(de.uni_koblenz.jgralab.VertexFilter<V> filter);
		/**
		 * adds the given vertex as <code>target</code> to this vertex, i.e. creates an
		 * <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge from this vertex to the given 
		 * one and returns the created edge.
		 * @return  a newly created edge of type <code>de.uni_koblenz.jgralab.demo.schema.Connection</code>
		 *          between this vertex and the given one.
		 */
		public de.uni_koblenz.jgralab.demo.schema.Connection add_target(de.uni_koblenz.jgralab.demo.schema.Node vertex);
		/**
		 * removes all target adjacences to all vertices by 
		 * deleting the <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edges of this vertex to 
		 * all other ones, but doesn't delete those vertices.
		 *
		 * @return the adjacent vertices prior to removal of incidences
		 */
		public java.util.List<? extends de.uni_koblenz.jgralab.demo.schema.Node> remove_target();
		/**
		 * removes the given vertex as <code>target</code> from this vertex, i.e. 
		 * deletes the <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge connections of this vertex with 
		 * the given one.
		 */
		public boolean remove_target(de.uni_koblenz.jgralab.demo.schema.Node vertex);
		/**
		 * @return an Iterable of all vertices adjacent to this one with the rolename 'target'
		 *         (connected with a <code>de.uni_koblenz.jgralab.demo.schema.Connection</code> edge).
		 */
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_target();
		
		public <V extends de.uni_koblenz.jgralab.demo.schema.Node> Iterable<V> get_target(de.uni_koblenz.jgralab.VertexFilter<V> filter);

	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type Connection or subtypes.
	 */
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Connection> getConnectionIncidences();
	
	/**
	 * Returns an Iterable for all incidence edges of this vertex that are of type Connection.
	 * @param direction EdgeDirection.IN or EdgeDirection.OUT, only edges of this direction will be included in the Iterable
	 */
	public Iterable<de.uni_koblenz.jgralab.demo.schema.Connection> getConnectionIncidences(EdgeDirection direction);
}
